name: DeepSource Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deepsource:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install DeepSource CLI
      - name: Install DeepSource CLI
        run: |
          curl -sSL https://deepsource.io/cli | sh  # Download DeepSource CLI
          chmod +x ./bin/deepsource  # Ensure the CLI is executable
          echo "$HOME/bin" >> $GITHUB_PATH  # Add the binary location to the PATH

      # Step 3: Verify Installation
      - name: Verify Installation
        run: ./bin/deepsource version  # Ensure the DeepSource CLI was installed correctly

      # Step 4: Set up DeepSource DSN
      - name: Set up DeepSource DSN
        run: |
          echo "$DEEPSOURCE_DSN" > ~/.deepsource-dsn

      # Step 5: Run DeepSource Scan
      - name: Run DeepSource Scan
        run: ./bin/deepsource analyze
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}  # Use the DSN from GitHub Secrets
